import { BROWSER_RECOVERY_BOOTSTRAP_STATEMENTS } from "./browser-recovery-schema.js";
import { ANALYTICS_SPACE_BOOTSTRAP_STATEMENTS } from "./analytics-space-schema.js";
import { ANALYTICS_SPACE_IDENTITY_NAMESPACE_BOOTSTRAP_STATEMENTS } from "./analytics-space-identity-namespace-schema.js";
import { ANALYTICS_WRITER_BOOTSTRAP_STATEMENTS } from "./analytics-writer-schema.js";
import { ANALYTICS_PROJECT_CATALOG_BOOTSTRAP_STATEMENTS } from "./analytics-project-catalog-schema.js";
import { ANALYTICS_MEASUREMENT_PLAN_BOOTSTRAP_STATEMENTS } from "./analytics-measurement-plan-schema.js";
import { ANALYTICS_SPACE_PLAN_BOOTSTRAP_STATEMENTS } from "./analytics-space-plan-schema.js";
import { ANALYTICS_SPACE_REPORT_BOOTSTRAP_STATEMENTS } from "./analytics-space-report-schema.js";
import { SEMANTIC_ANALYTICS_PORTFOLIO_FUNNEL_BOOTSTRAP_STATEMENTS } from "./semantic-analytics-portfolio-funnel-schema.js";
import { SEMANTIC_ANALYTICS_RECEIPT_BOOTSTRAP_STATEMENTS } from "./semantic-analytics-receipt-schema.js";
import { SEMANTIC_ANALYTICS_OBSERVATION_BOOTSTRAP_STATEMENTS } from "./semantic-analytics-observation-schema.js";
import { SEMANTIC_ANALYTICS_PRODUCER_OBSERVATION_BOOTSTRAP_STATEMENTS } from "./semantic-analytics-producer-observation-schema.js";
import { SEMANTIC_ANALYTICS_ORPHAN_SWEEP_BOOTSTRAP_STATEMENTS } from "./semantic-analytics-orphan-sweep-schema.js";
import { SEMANTIC_ANALYTICS_RAW_RETENTION_BOOTSTRAP_STATEMENTS } from "./semantic-analytics-raw-retention-schema.js";
import { PROJECT_OBJECT_ERASURE_BOOTSTRAP_STATEMENTS } from "./project-object-erasure-schema.js";
import { SEMANTIC_ANALYTICS_LOSS_BOOTSTRAP_STATEMENTS } from "./semantic-analytics-loss-schema.js";
import { SEMANTIC_ANALYTICS_FUNNEL_BOOTSTRAP_STATEMENTS } from "./semantic-analytics-funnel-schema.js";
import { ANALYTICS_IDENTITY_CONTEXT_BOOTSTRAP_STATEMENTS } from "./analytics-identity-context-schema.js";
import { ANALYTICS_IDENTITY_REVOCATION_BOOTSTRAP_STATEMENTS } from "./analytics-identity-revocation-schema.js";
import { SEMANTIC_ANALYTICS_IDENTITY_RECEIPT_BOOTSTRAP_STATEMENTS } from "./semantic-analytics-identity-receipt-schema.js";
import { ANALYTICS_IDENTITY_EPOCH_BOOTSTRAP_STATEMENTS } from "./analytics-identity-epoch-schema.js";
import { SEMANTIC_ANALYTICS_RECEIPT_SUBJECT_BOOTSTRAP_STATEMENTS } from "./semantic-analytics-receipt-subject-schema.js";
import { ANALYTICS_IDENTITY_ASSOCIATION_BOOTSTRAP_STATEMENTS } from "./analytics-identity-association-schema.js";
import { ANALYTICS_SUBJECT_ERASURE_BOOTSTRAP_STATEMENTS } from "./analytics-subject-erasure-schema.js";
import { AVAILABILITY_CHECK_BOOTSTRAP_STATEMENTS } from "./availability-check-bootstrap-statements.js";
import { ANALYTICS_BOOTSTRAP_STATEMENTS } from "./analytics-bootstrap-statements.js";
import { WORKER_JOB_BOOTSTRAP_STATEMENTS } from "./worker-job-schema.js";
import { OPENAI_OAUTH_BOOTSTRAP_STATEMENTS } from "./openai-oauth-bootstrap-statements.js";
import { STORAGE_BOOTSTRAP_STATEMENTS as CORE_STORAGE_BOOTSTRAP_STATEMENTS } from "./storage-bootstrap-statements.js";

export const STORAGE_BOOTSTRAP_STATEMENTS = [
  ...CORE_STORAGE_BOOTSTRAP_STATEMENTS,
  ...BROWSER_RECOVERY_BOOTSTRAP_STATEMENTS,
  ...OPENAI_OAUTH_BOOTSTRAP_STATEMENTS,
  ...AVAILABILITY_CHECK_BOOTSTRAP_STATEMENTS,
  ...ANALYTICS_BOOTSTRAP_STATEMENTS,
  ...WORKER_JOB_BOOTSTRAP_STATEMENTS,
  ...ANALYTICS_SPACE_BOOTSTRAP_STATEMENTS,
  ...ANALYTICS_SPACE_IDENTITY_NAMESPACE_BOOTSTRAP_STATEMENTS,
  ...ANALYTICS_WRITER_BOOTSTRAP_STATEMENTS,
  ...ANALYTICS_PROJECT_CATALOG_BOOTSTRAP_STATEMENTS,
  ...ANALYTICS_MEASUREMENT_PLAN_BOOTSTRAP_STATEMENTS,
  ...ANALYTICS_SPACE_PLAN_BOOTSTRAP_STATEMENTS,
  ...ANALYTICS_SPACE_REPORT_BOOTSTRAP_STATEMENTS,
  ...SEMANTIC_ANALYTICS_PORTFOLIO_FUNNEL_BOOTSTRAP_STATEMENTS,
  ...SEMANTIC_ANALYTICS_RECEIPT_BOOTSTRAP_STATEMENTS,
  ...SEMANTIC_ANALYTICS_OBSERVATION_BOOTSTRAP_STATEMENTS,
  ...SEMANTIC_ANALYTICS_PRODUCER_OBSERVATION_BOOTSTRAP_STATEMENTS,
  ...SEMANTIC_ANALYTICS_ORPHAN_SWEEP_BOOTSTRAP_STATEMENTS,
  ...SEMANTIC_ANALYTICS_RAW_RETENTION_BOOTSTRAP_STATEMENTS,
  ...PROJECT_OBJECT_ERASURE_BOOTSTRAP_STATEMENTS,
  ...SEMANTIC_ANALYTICS_LOSS_BOOTSTRAP_STATEMENTS,
  ...SEMANTIC_ANALYTICS_FUNNEL_BOOTSTRAP_STATEMENTS,
  ...ANALYTICS_IDENTITY_CONTEXT_BOOTSTRAP_STATEMENTS,
  ...ANALYTICS_IDENTITY_REVOCATION_BOOTSTRAP_STATEMENTS,
  ...SEMANTIC_ANALYTICS_IDENTITY_RECEIPT_BOOTSTRAP_STATEMENTS,
  ...ANALYTICS_IDENTITY_EPOCH_BOOTSTRAP_STATEMENTS,
  ...SEMANTIC_ANALYTICS_RECEIPT_SUBJECT_BOOTSTRAP_STATEMENTS,
  ...ANALYTICS_IDENTITY_ASSOCIATION_BOOTSTRAP_STATEMENTS,
  ...ANALYTICS_SUBJECT_ERASURE_BOOTSTRAP_STATEMENTS
] as const;
