import { mkdtemp, mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";

import { describe, expect, it, vi } from "vitest";

import { ingestCommand } from "../../../apps/cli/src/ingest-command.js";

async function createIngestFixtureRepository(): Promise<string> {
  const rootDirectory = await mkdtemp(join(tmpdir(), "debugbundle-ingest-"));

  await mkdir(join(rootDirectory, ".debugbundle", "local", "events"), { recursive: true });
  await writeFile(
    join(rootDirectory, ".debugbundle", "profile.json"),
    `${JSON.stringify(
      {
        profile_version: "v1",
        project: {
          name: "Checkout App",
          repo_url: "",
          primary_languages: ["TypeScript"],
          package_managers: ["pnpm"],
          deployment_targets: ["docker-compose"]
        },
        services: [
          {
            name: "checkout-api",
            kind: "backend",
            runtime: "php",
            framework: "laravel",
            paths: ["apps/api"],
            owns_routes: [],
            depends_on: []
          }
        ],
        infrastructure: {
          databases: [],
          queues: [],
          object_storage: [],
          external_services: []
        },
        critical_paths: [],
        repo: {
          root_paths: ["apps", "packages"],
          generated_paths: [".debugbundle", ".agents/skills/debugbundle"],
          do_not_edit_paths: [
            ".debugbundle/bundles",
            ".debugbundle/local/events",
            ".debugbundle/local/state.json",
            ".debugbundle/local/browser-relay-spool"
          ]
        },
        developer_workflows: {
          install: "pnpm install",
          build: "make build",
          test: "make test",
          lint: "make lint"
        },
        debugbundle: {
          profile_owner: "unassigned",
          last_reviewed_at: "2026-03-21T00:00:00.000Z",
          validation_status: "agent-validated",
          skill_path: ".agents/skills/debugbundle",
          notes: "Generated by debugbundle setup."
        }
      },
      null,
      2
    )}\n`,
    "utf8"
  );

  return rootDirectory;
}

describe("cli ingest command", () => {
  it("ingests debugbundle ndjson entries into local events and processes them into local bundles", async () => {
    const rootDirectory = await createIngestFixtureRepository();
    const logPath = join(rootDirectory, "var", "log", "debugbundle.ndjson");

    await mkdir(join(rootDirectory, "var", "log"), { recursive: true });
    await writeFile(
      logPath,
      `${JSON.stringify({
        type: "error",
        error_type: "TypeError",
        message: "Checkout failed while applying discount",
        stack: "TypeError: Checkout failed while applying discount\\n    at checkout.php:42",
        file: "/srv/app/checkout.php",
        line: 42,
        timestamp: "2026-03-21T10:20:30.000Z",
        environment: "production",
        service: "checkout-api"
      })}\n`,
      "utf8"
    );

    const result = await ingestCommand(
      {
        filePath: logPath,
        format: "debugbundle-ndjson",
        json: true
      },
      {
        cwd: () => rootDirectory
      }
    );

    expect(result.exitCode).toBe(0);

    const parsedOutput = JSON.parse(result.output) as {
      status: string;
      format: string;
      events_ingested: number;
      event_file: string;
      process: {
        processed: boolean;
        events_processed: number;
        incidents_processed: number;
      };
    };

    expect(parsedOutput).toMatchObject({
      status: "ok",
      format: "debugbundle-ndjson",
      events_ingested: 1,
      process: {
        processed: true,
        events_processed: 1,
        incidents_processed: 1
      }
    });

    const eventFiles = await readdir(join(rootDirectory, ".debugbundle", "local", "events"));
    expect(eventFiles).toEqual([parsedOutput.event_file]);

    const storedBatch = JSON.parse(
      await readFile(join(rootDirectory, ".debugbundle", "local", "events", parsedOutput.event_file), "utf8")
    ) as Array<{
      project_id: string;
      service: { name: string; environment: string };
      payload: { name: string; message: string };
    }>;

    expect(storedBatch).toHaveLength(1);
    expect(storedBatch[0]?.project_id).toMatch(
      /^[0-9a-f]{8}-[0-9a-f]{4}-5[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/
    );
    expect(storedBatch[0]?.service).toMatchObject({
      name: "checkout-api",
      environment: "production"
    });
    expect(storedBatch[0]?.payload).toMatchObject({
      name: "TypeError",
      message: "Checkout failed while applying discount"
    });

    const state = JSON.parse(await readFile(join(rootDirectory, ".debugbundle", "local", "state.json"), "utf8")) as {
      incidents: Record<string, { service_name: string }>;
    };
    expect(Object.values(state.incidents)).toEqual([
      expect.objectContaining({
        service_name: "checkout-api"
      })
    ]);
  });

  it("parses php error logs into backend exception events and forwards them to process", async () => {
    const rootDirectory = await createIngestFixtureRepository();
    const logPath = join(rootDirectory, "var", "log", "php_errors.log");
    const processCommand = vi.fn().mockResolvedValue({
      exitCode: 0,
      output: JSON.stringify({
        status: "ok",
        processed: true,
        files_processed: 1,
        events_processed: 1,
        incidents_processed: 1,
        services: [{ service: "checkout-api", incidents: 1 }],
        last_processed_event_file: "placeholder.events.json"
      })
    });

    await mkdir(join(rootDirectory, "var", "log"), { recursive: true });
    await writeFile(
      logPath,
      [
        "[21-Mar-2026 10:20:30 UTC] PHP Fatal error:  Uncaught TypeError: Checkout failed in /srv/app/checkout.php:42",
        "Stack trace:",
        "#0 /srv/app/index.php(10): CheckoutService->run()",
        "#1 {main}",
        '  thrown in /srv/app/checkout.php on line 42'
      ].join("\n"),
      "utf8"
    );

    const result = await ingestCommand(
      {
        filePath: logPath,
        format: "php-error",
        json: true
      },
      {
        cwd: () => rootDirectory,
        processCommand
      }
    );

    expect(result.exitCode).toBe(0);
    expect(processCommand).toHaveBeenCalledWith({ json: true });

    const eventFiles = await readdir(join(rootDirectory, ".debugbundle", "local", "events"));
    expect(eventFiles).toHaveLength(1);
    const storedBatch = JSON.parse(
      await readFile(join(rootDirectory, ".debugbundle", "local", "events", eventFiles[0] ?? ""), "utf8")
    ) as Array<{
      event_type: string;
      payload: { name: string; message: string; stack: string };
    }>;

    expect(storedBatch[0]).toMatchObject({
      event_type: "backend_exception",
      payload: {
        name: "TypeError",
        message: "Checkout failed",
        stack: expect.stringContaining("CheckoutService->run")
      }
    });
  });

  it("parses apache error logs into backend exception events", async () => {
    const rootDirectory = await createIngestFixtureRepository();
    const logPath = join(rootDirectory, "var", "log", "apache_error.log");
    const processCommand = vi.fn().mockResolvedValue({
      exitCode: 0,
      output: JSON.stringify({
        status: "ok",
        processed: true,
        files_processed: 1,
        events_processed: 1,
        incidents_processed: 1,
        services: [{ service: "checkout-api", incidents: 1 }],
        last_processed_event_file: "placeholder.events.json"
      })
    });

    await mkdir(join(rootDirectory, "var", "log"), { recursive: true });
    await writeFile(
      logPath,
      "[Sat Mar 21 10:20:30.123456 2026] [php:error] [pid 123] [client 127.0.0.1:1234] PHP Fatal error: Uncaught RuntimeException: Apache checkout failed in /srv/app/public/index.php:17",
      "utf8"
    );

    const result = await ingestCommand(
      {
        filePath: logPath,
        format: "apache-error",
        json: true
      },
      {
        cwd: () => rootDirectory,
        processCommand
      }
    );

    expect(result.exitCode).toBe(0);

    const eventFiles = await readdir(join(rootDirectory, ".debugbundle", "local", "events"));
    const storedBatch = JSON.parse(
      await readFile(join(rootDirectory, ".debugbundle", "local", "events", eventFiles[0] ?? ""), "utf8")
    ) as Array<{
      payload: { name: string; message: string };
    }>;

    expect(storedBatch[0]?.payload).toMatchObject({
      name: "RuntimeException",
      message: "Apache checkout failed"
    });
  });

  it("rejects unsupported ingest formats", async () => {
    const rootDirectory = await createIngestFixtureRepository();
    const logPath = join(rootDirectory, "var", "log", "unsupported.log");

    await mkdir(join(rootDirectory, "var", "log"), { recursive: true });
    await writeFile(logPath, "plain text", "utf8");

    const result = await ingestCommand(
      {
        filePath: logPath,
        format: "syslog"
      },
      {
        cwd: () => rootDirectory
      }
    );

    expect(result).toEqual({
      exitCode: 4,
      output: "Unsupported --format value. Expected one of: debugbundle-ndjson, php-error, apache-error."
    });
  });

  it("returns a validation error when the log file contains no supported events", async () => {
    const rootDirectory = await createIngestFixtureRepository();
    const logPath = join(rootDirectory, "var", "log", "empty.ndjson");

    await mkdir(join(rootDirectory, "var", "log"), { recursive: true });
    await writeFile(logPath, "\n\n\n", "utf8");

    const result = await ingestCommand(
      {
        filePath: logPath,
        format: "debugbundle-ndjson"
      },
      {
        cwd: () => rootDirectory
      }
    );

    expect(result).toEqual({
      exitCode: 4,
      output: "No supported events were found in the input file."
    });
  });

  it("returns an error when the profile is missing", async () => {
    const rootDirectory = await mkdtemp(join(tmpdir(), "debugbundle-ingest-no-profile-"));
    const logPath = join(rootDirectory, "var", "log", "debugbundle.ndjson");

    await mkdir(join(rootDirectory, "var", "log"), { recursive: true });
    await writeFile(
      logPath,
      `${JSON.stringify({
        type: "error",
        error_type: "TypeError",
        message: "fail",
        stack: "TypeError: fail",
        file: "/app.php",
        line: 1,
        timestamp: "2026-03-21T10:00:00.000Z",
        environment: "production",
        service: "api"
      })}\n`,
      "utf8"
    );

    const result = await ingestCommand(
      {
        filePath: logPath,
        format: "debugbundle-ndjson"
      },
      {
        cwd: () => rootDirectory
      }
    );

    expect(result.exitCode).toBe(1);
    expect(result.output).toMatch(/profile\.json/i);
  });

  it("returns an error when the source log file does not exist", async () => {
    const rootDirectory = await createIngestFixtureRepository();

    const result = await ingestCommand(
      {
        filePath: join(rootDirectory, "var", "log", "nonexistent.ndjson"),
        format: "debugbundle-ndjson"
      },
      {
        cwd: () => rootDirectory
      }
    );

    expect(result.exitCode).toBe(1);
  });

  it("surfaces process command failures after successful ingestion", async () => {
    const rootDirectory = await createIngestFixtureRepository();
    const logPath = join(rootDirectory, "var", "log", "debugbundle.ndjson");

    await mkdir(join(rootDirectory, "var", "log"), { recursive: true });
    await writeFile(
      logPath,
      `${JSON.stringify({
        type: "error",
        error_type: "TypeError",
        message: "Checkout failed",
        stack: "TypeError: Checkout failed\\n    at checkout.php:42",
        file: "/srv/app/checkout.php",
        line: 42,
        timestamp: "2026-03-21T10:20:30.000Z",
        environment: "production",
        service: "checkout-api"
      })}\n`,
      "utf8"
    );

    const result = await ingestCommand(
      {
        filePath: logPath,
        format: "debugbundle-ndjson",
        json: true
      },
      {
        cwd: () => rootDirectory,
        processCommand: vi.fn().mockResolvedValue({
          exitCode: 1,
          output: "process_failed"
        })
      }
    );

    expect(result.exitCode).toBe(1);
    expect(result.output).toBe("process_failed");
  });

  it("produces human-readable output when json flag is omitted", async () => {
    const rootDirectory = await createIngestFixtureRepository();
    const logPath = join(rootDirectory, "var", "log", "debugbundle.ndjson");

    await mkdir(join(rootDirectory, "var", "log"), { recursive: true });
    await writeFile(
      logPath,
      `${JSON.stringify({
        type: "error",
        error_type: "TypeError",
        message: "Checkout failed",
        stack: "TypeError: Checkout failed\\n    at checkout.php:42",
        file: "/srv/app/checkout.php",
        line: 42,
        timestamp: "2026-03-21T10:20:30.000Z",
        environment: "production",
        service: "checkout-api"
      })}\n`,
      "utf8"
    );

    const result = await ingestCommand(
      {
        filePath: logPath,
        format: "debugbundle-ndjson"
      },
      {
        cwd: () => rootDirectory
      }
    );

    expect(result.exitCode).toBe(0);
    expect(result.output).toContain("Ingested 1 events");
    expect(result.output).toContain("debugbundle-ndjson");
    expect(result.output).toContain("Processed");
  });
});