import { mkdtemp, mkdir, readFile, readdir, stat, truncate, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";

import { describe, expect, it, vi } from "vitest";

import { watchCommand } from "../../../apps/cli/src/watch-command.js";

async function createWatchFixtureRepository(): Promise<string> {
  const rootDirectory = await mkdtemp(join(tmpdir(), "debugbundle-watch-"));

  await mkdir(join(rootDirectory, ".debugbundle", "local", "events"), { recursive: true });
  await mkdir(join(rootDirectory, ".debugbundle", "local"), { recursive: true });
  await writeFile(
    join(rootDirectory, ".debugbundle", "profile.json"),
    `${JSON.stringify(
      {
        profile_version: "v1",
        project: {
          name: "Checkout App",
          repo_url: "",
          primary_languages: ["TypeScript"],
          package_managers: ["pnpm"],
          deployment_targets: ["docker-compose"]
        },
        services: [
          {
            name: "checkout-api",
            kind: "backend",
            runtime: "php",
            framework: "laravel",
            paths: ["apps/api"],
            owns_routes: [],
            depends_on: []
          }
        ],
        infrastructure: {
          databases: [],
          queues: [],
          object_storage: [],
          external_services: []
        },
        critical_paths: [],
        repo: {
          root_paths: ["apps", "packages"],
          generated_paths: [".debugbundle", ".agents/skills/debugbundle"],
          do_not_edit_paths: [
            ".debugbundle/bundles",
            ".debugbundle/local/events",
            ".debugbundle/local/state.json",
            ".debugbundle/local/browser-relay-spool"
          ]
        },
        developer_workflows: {
          install: "pnpm install",
          build: "make build",
          test: "make test",
          lint: "make lint"
        },
        debugbundle: {
          profile_owner: "unassigned",
          last_reviewed_at: "2026-03-21T00:00:00.000Z",
          validation_status: "agent-validated",
          skill_path: ".agents/skills/debugbundle",
          notes: "Generated by debugbundle setup."
        }
      },
      null,
      2
    )}\n`,
    "utf8"
  );
  await writeFile(
    join(rootDirectory, ".debugbundle", "local", "connection.json"),
    `${JSON.stringify(
      {
        mode: "local-only",
        cloud_project_id: null,
        cloud_base_url: null,
        environments: {
          local: { delivery: "local-only" },
          development: { delivery: "local-only" },
          staging: { delivery: "local-only" },
          production: { delivery: "local-only" }
        }
      },
      null,
      2
    )}\n`,
    "utf8"
  );

  return rootDirectory;
}

describe("cli watch command", () => {
  it("tails only appended log content and processes it into local bundles", async () => {
    const rootDirectory = await createWatchFixtureRepository();
    const logPath = join(rootDirectory, "var", "log", "debugbundle.ndjson");
    const abortController = new AbortController();
    let sleepCount = 0;

    await mkdir(join(rootDirectory, "var", "log"), { recursive: true });
    await writeFile(
      logPath,
      `${JSON.stringify({
        type: "error",
        error_type: "IgnoredError",
        message: "old event",
        stack: "IgnoredError: old event",
        file: "/srv/app/old.php",
        line: 1,
        timestamp: "2026-03-21T10:00:00.000Z",
        environment: "production",
        service: "checkout-api"
      })}\n`,
      "utf8"
    );

    const resultPromise = watchCommand(
      {
        logPath,
        format: "debugbundle-ndjson",
        json: true
      },
      {
        cwd: () => rootDirectory,
        pollIntervalMs: 1,
        signal: abortController.signal,
        sleep: async () => {
          sleepCount += 1;
          if (sleepCount === 1) {
            await writeFile(
              logPath,
              `${await readFile(logPath, "utf8")}${JSON.stringify({
                type: "error",
                error_type: "TypeError",
                message: "Checkout failed while applying discount",
                stack: "TypeError: Checkout failed while applying discount\\n    at checkout.php:42",
                file: "/srv/app/checkout.php",
                line: 42,
                timestamp: "2026-03-21T10:20:30.000Z",
                environment: "production",
                service: "checkout-api"
              })}\n`,
              "utf8"
            );
            return;
          }

          abortController.abort();
        }
      }
    );

    const result = await resultPromise;

    expect(result.exitCode).toBe(0);
    const parsedOutput = JSON.parse(result.output) as {
      status: string;
      format: string;
      events_ingested: number;
      batches_written: number;
      process_runs: number;
    };
    expect(parsedOutput).toMatchObject({
      status: "ok",
      format: "debugbundle-ndjson",
      events_ingested: 1,
      batches_written: 1,
      process_runs: 1
    });

    const eventFiles = await readdir(join(rootDirectory, ".debugbundle", "local", "events"));
    expect(eventFiles).toHaveLength(1);

    const state = JSON.parse(await readFile(join(rootDirectory, ".debugbundle", "local", "state.json"), "utf8")) as {
      incidents: Record<string, { occurrence_count: number; source_events: Array<{ payload: { message: string } }> }>;
    };
    expect(Object.values(state.incidents)).toEqual([
      expect.objectContaining({
        occurrence_count: 1,
        source_events: [
          expect.objectContaining({
            payload: expect.objectContaining({
              message: "Checkout failed while applying discount"
            })
          })
        ]
      })
    ]);
  });

  it("resets the tail offset when the watched file is truncated and rewritten", async () => {
    const rootDirectory = await createWatchFixtureRepository();
    const logPath = join(rootDirectory, "var", "log", "debugbundle.ndjson");
    const abortController = new AbortController();
    let sleepCount = 0;
    const processCommand = vi.fn()
      .mockResolvedValueOnce({
        exitCode: 0,
        output: JSON.stringify({
          status: "ok",
          processed: true,
          files_processed: 1,
          events_processed: 1,
          incidents_processed: 1,
          services: [{ service: "checkout-api", incidents: 1 }],
          last_processed_event_file: "first.events.json"
        })
      })
      .mockResolvedValueOnce({
        exitCode: 0,
        output: JSON.stringify({
          status: "ok",
          processed: true,
          files_processed: 1,
          events_processed: 1,
          incidents_processed: 1,
          services: [{ service: "checkout-api", incidents: 1 }],
          last_processed_event_file: "second.events.json"
        })
      });

    await mkdir(join(rootDirectory, "var", "log"), { recursive: true });
    await writeFile(logPath, "", "utf8");

    const resultPromise = watchCommand(
      {
        logPath,
        format: "debugbundle-ndjson",
        json: true
      },
      {
        cwd: () => rootDirectory,
        processCommand,
        pollIntervalMs: 1,
        signal: abortController.signal,
        sleep: async () => {
          sleepCount += 1;
          if (sleepCount === 1) {
            await writeFile(
              logPath,
              `${JSON.stringify({
                type: "error",
                error_type: "TypeError",
                message: "first event",
                stack: "TypeError: first event",
                file: "/srv/app/first.php",
                line: 1,
                timestamp: "2026-03-21T10:20:30.000Z",
                environment: "production",
                service: "checkout-api"
              })}\n`,
              "utf8"
            );
            return;
          }

          if (sleepCount === 2) {
            await truncate(logPath, 0);
            await writeFile(
              logPath,
              `${JSON.stringify({
                type: "error",
                error_type: "RuntimeException",
                message: "second event after rotation",
                stack: "RuntimeException: second event after rotation",
                file: "/srv/app/second.php",
                line: 2,
                timestamp: "2026-03-21T10:21:30.000Z",
                environment: "production",
                service: "checkout-api"
              })}\n`,
              "utf8"
            );
            return;
          }

          abortController.abort();
        }
      }
    );

    const result = await resultPromise;

    expect(result.exitCode).toBe(0);
    expect(processCommand).toHaveBeenCalledTimes(2);

    const eventFiles = await readdir(join(rootDirectory, ".debugbundle", "local", "events"));
    expect(eventFiles).toHaveLength(2);
    for (const eventFile of eventFiles) {
      expect((await stat(join(rootDirectory, ".debugbundle", "local", "events", eventFile))).size).toBeGreaterThan(0);
    }
  });

  it("rejects unsupported watch formats", async () => {
    const rootDirectory = await createWatchFixtureRepository();
    const logPath = join(rootDirectory, "var", "log", "unsupported.log");

    await mkdir(join(rootDirectory, "var", "log"), { recursive: true });
    await writeFile(logPath, "plain text", "utf8");

    const result = await watchCommand(
      {
        logPath,
        format: "syslog"
      },
      {
        cwd: () => rootDirectory
      }
    );

    expect(result).toEqual({
      exitCode: 4,
      output: "Unsupported --format value. Expected one of: debugbundle-ndjson, php-error, apache-error."
    });
  });

  it("ships appended log events to cloud in --cloud mode without writing local event batches", async () => {
    const rootDirectory = await createWatchFixtureRepository();
    const logPath = join(rootDirectory, "var", "log", "debugbundle.ndjson");
    const abortController = new AbortController();
    let sleepCount = 0;
    const sendEvents = vi.fn().mockResolvedValue({
      accepted: 1,
      rejected: 0,
      errors: []
    });

    await writeFile(
      join(rootDirectory, ".debugbundle", "local", "connection.json"),
      `${JSON.stringify(
        {
          mode: "connected",
          cloud_project_id: "proj_cloud_123",
          cloud_base_url: "https://api.debugbundle.test",
          environments: {
            local: { delivery: "local-only" },
            development: { delivery: "local-only" },
            staging: { delivery: "local-only" },
            production: { delivery: "cloud-enabled" }
          }
        },
        null,
        2
      )}\n`,
      "utf8"
    );

    await mkdir(join(rootDirectory, "var", "log"), { recursive: true });
    await writeFile(logPath, "", "utf8");

    const resultPromise = watchCommand(
      {
        logPath,
        format: "debugbundle-ndjson",
        cloud: true,
        json: true
      },
      {
        cwd: () => rootDirectory,
        pollIntervalMs: 1,
        readEnv: (name) => (name === "DEBUGBUNDLE_PROJECT_TOKEN" ? "dbundle_proj_secret" : undefined),
        sendEvents,
        signal: abortController.signal,
        sleep: async () => {
          sleepCount += 1;
          if (sleepCount === 1) {
            await writeFile(
              logPath,
              `${JSON.stringify({
                type: "error",
                error_type: "TypeError",
                message: "Checkout failed in cloud tail",
                stack: "TypeError: Checkout failed in cloud tail",
                file: "/srv/app/checkout.php",
                line: 42,
                timestamp: "2026-03-21T10:20:30.000Z",
                environment: "production",
                service: "checkout-api"
              })}\n`,
              "utf8"
            );
            return;
          }

          abortController.abort();
        }
      }
    );

    const result = await resultPromise;

    expect(result.exitCode).toBe(0);
    expect(sendEvents).toHaveBeenCalledTimes(1);
    expect(sendEvents).toHaveBeenCalledWith({
      baseUrl: "https://api.debugbundle.test",
      projectToken: "dbundle_proj_secret",
      events: [
        expect.objectContaining({
          event_type: "backend_exception",
          payload: expect.objectContaining({
            message: "Checkout failed in cloud tail"
          })
        })
      ]
    });

    const parsedOutput = JSON.parse(result.output) as {
      status: string;
      mode: string;
      events_ingested: number;
      batches_shipped: number;
    };
    expect(parsedOutput).toMatchObject({
      status: "ok",
      mode: "cloud",
      events_ingested: 1,
      batches_shipped: 1
    });
    expect(await readdir(join(rootDirectory, ".debugbundle", "local", "events"))).toEqual([]);
  });

  it("requires connected config and DEBUGBUNDLE_PROJECT_TOKEN for --cloud mode", async () => {
    const rootDirectory = await createWatchFixtureRepository();
    const logPath = join(rootDirectory, "var", "log", "debugbundle.ndjson");

    await mkdir(join(rootDirectory, "var", "log"), { recursive: true });
    await writeFile(logPath, "", "utf8");

    const result = await watchCommand(
      {
        logPath,
        format: "debugbundle-ndjson",
        cloud: true
      },
      {
        cwd: () => rootDirectory,
        readEnv: () => undefined
      }
    );

    expect(result).toEqual({
      exitCode: 4,
      output: "Cloud watch requires a connected project with cloud delivery enabled and DEBUGBUNDLE_PROJECT_TOKEN set."
    });
  });

  it("buffers partial lines across poll cycles and processes them once a newline arrives", async () => {
    const rootDirectory = await createWatchFixtureRepository();
    const logPath = join(rootDirectory, "var", "log", "debugbundle.ndjson");
    const abortController = new AbortController();
    let sleepCount = 0;
    const processCommand = vi.fn().mockResolvedValue({
      exitCode: 0,
      output: JSON.stringify({
        status: "ok",
        processed: true,
        files_processed: 1,
        events_processed: 1,
        incidents_processed: 1,
        services: [{ service: "checkout-api", incidents: 1 }],
        last_processed_event_file: "partial.events.json"
      })
    });

    const fullEntry = JSON.stringify({
      type: "error",
      error_type: "TypeError",
      message: "Partial line test",
      stack: "TypeError: Partial line test",
      file: "/srv/app/partial.php",
      line: 1,
      timestamp: "2026-03-21T10:20:30.000Z",
      environment: "production",
      service: "checkout-api"
    });

    await mkdir(join(rootDirectory, "var", "log"), { recursive: true });
    await writeFile(logPath, "", "utf8");

    const resultPromise = watchCommand(
      {
        logPath,
        format: "debugbundle-ndjson",
        json: true
      },
      {
        cwd: () => rootDirectory,
        processCommand,
        pollIntervalMs: 1,
        signal: abortController.signal,
        sleep: async () => {
          sleepCount += 1;
          if (sleepCount === 1) {
            await writeFile(logPath, fullEntry.slice(0, 30), "utf8");
            return;
          }

          if (sleepCount === 2) {
            await writeFile(logPath, `${fullEntry}\n`, "utf8");
            return;
          }

          abortController.abort();
        }
      }
    );

    const result = await resultPromise;

    expect(result.exitCode).toBe(0);
    expect(processCommand).toHaveBeenCalledTimes(1);

    const parsedOutput = JSON.parse(result.output) as {
      events_ingested: number;
      batches_written: number;
    };
    expect(parsedOutput.events_ingested).toBe(1);
    expect(parsedOutput.batches_written).toBe(1);
  });

  it("returns an error when cloud API rejects the ingested batch", async () => {
    const rootDirectory = await createWatchFixtureRepository();
    const logPath = join(rootDirectory, "var", "log", "debugbundle.ndjson");
    const abortController = new AbortController();
    let sleepCount = 0;

    await writeFile(
      join(rootDirectory, ".debugbundle", "local", "connection.json"),
      `${JSON.stringify(
        {
          mode: "connected",
          cloud_project_id: "proj_cloud_reject",
          cloud_base_url: "https://api.debugbundle.test",
          environments: {
            local: { delivery: "local-only" },
            development: { delivery: "local-only" },
            staging: { delivery: "local-only" },
            production: { delivery: "cloud-enabled" }
          }
        },
        null,
        2
      )}\n`,
      "utf8"
    );

    await mkdir(join(rootDirectory, "var", "log"), { recursive: true });
    await writeFile(logPath, "", "utf8");

    const resultPromise = watchCommand(
      {
        logPath,
        format: "debugbundle-ndjson",
        cloud: true,
        json: true
      },
      {
        cwd: () => rootDirectory,
        pollIntervalMs: 1,
        readEnv: (name) => (name === "DEBUGBUNDLE_PROJECT_TOKEN" ? "dbundle_proj_secret" : undefined),
        sendEvents: vi.fn().mockResolvedValue({
          accepted: 0,
          rejected: 1,
          errors: [{ index: 0, reason: "quota_exceeded" }]
        }),
        signal: abortController.signal,
        sleep: async () => {
          sleepCount += 1;
          if (sleepCount === 1) {
            await writeFile(
              logPath,
              `${JSON.stringify({
                type: "error",
                error_type: "TypeError",
                message: "Rejected event",
                stack: "TypeError: Rejected event",
                file: "/srv/app/reject.php",
                line: 1,
                timestamp: "2026-03-21T10:20:30.000Z",
                environment: "production",
                service: "checkout-api"
              })}\n`,
              "utf8"
            );
            return;
          }

          abortController.abort();
        }
      }
    );

    const result = await resultPromise;

    expect(result.exitCode).toBe(1);
    expect(result.output).toContain("did not fully accept");
  });

  it("produces human-readable output when json flag is omitted", async () => {
    const rootDirectory = await createWatchFixtureRepository();
    const logPath = join(rootDirectory, "var", "log", "debugbundle.ndjson");
    const abortController = new AbortController();
    let sleepCount = 0;

    await mkdir(join(rootDirectory, "var", "log"), { recursive: true });
    await writeFile(logPath, "", "utf8");

    const resultPromise = watchCommand(
      {
        logPath,
        format: "debugbundle-ndjson"
      },
      {
        cwd: () => rootDirectory,
        pollIntervalMs: 1,
        signal: abortController.signal,
        sleep: async () => {
          sleepCount += 1;
          if (sleepCount === 1) {
            await writeFile(
              logPath,
              `${JSON.stringify({
                type: "error",
                error_type: "TypeError",
                message: "Human output test",
                stack: "TypeError: Human output test",
                file: "/srv/app/human.php",
                line: 1,
                timestamp: "2026-03-21T10:20:30.000Z",
                environment: "production",
                service: "checkout-api"
              })}\n`,
              "utf8"
            );
            return;
          }

          abortController.abort();
        }
      }
    );

    const result = await resultPromise;

    expect(result.exitCode).toBe(0);
    expect(result.output).toContain("Watched");
    expect(result.output).toContain("debugbundle-ndjson");
    expect(result.output).toContain("Ingested 1 events");
    expect(result.output).toContain("Ran local processing");
  });
});