import { mkdtemp, mkdir, readFile, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";

import { describe, expect, it, vi } from "vitest";

import { CliAuthStateError } from "../../../apps/cli/src/auth-state.js";
import { connectCommand } from "../../../apps/cli/src/connect-command.js";
import { ProjectManagementApiError } from "../../../packages/project-management-client/src/index.js";
import { TokenManagementApiError } from "../../../packages/token-management/src/index.js";

async function createConnectFixtureRepository(): Promise<string> {
  const rootDirectory = await mkdtemp(join(tmpdir(), "debugbundle-connect-"));

  await mkdir(join(rootDirectory, ".debugbundle", "local"), { recursive: true });
  await writeFile(
    join(rootDirectory, ".debugbundle", "profile.json"),
    `${JSON.stringify(
      {
        profile_version: "v1",
        project: {
          name: "Checkout App",
          repo_url: "",
          primary_languages: ["TypeScript"],
          package_managers: ["pnpm"],
          deployment_targets: ["docker-compose"]
        },
        services: [],
        infrastructure: {
          databases: [],
          queues: [],
          object_storage: [],
          external_services: []
        },
        critical_paths: [],
        repo: {
          root_paths: ["apps", "packages"],
          generated_paths: [".debugbundle", ".agents/skills/debugbundle"],
          do_not_edit_paths: [
            ".debugbundle/bundles",
            ".debugbundle/local/events",
            ".debugbundle/local/state.json",
            ".debugbundle/local/browser-relay-spool"
          ]
        },
        developer_workflows: {
          install: "pnpm install",
          build: "make build",
          test: "make test",
          lint: "make lint"
        },
        debugbundle: {
          profile_owner: "unassigned",
          last_reviewed_at: "2026-03-21T00:00:00.000Z",
          validation_status: "static-analysis-only",
          skill_path: ".agents/skills/debugbundle",
          notes: "Generated by debugbundle setup."
        }
      },
      null,
      2
    )}\n`,
    "utf8"
  );
  await writeFile(
    join(rootDirectory, ".debugbundle", "local", "connection.json"),
    `${JSON.stringify(
      {
        mode: "local-only",
        cloud_project_id: null,
        cloud_base_url: null,
        environments: {
          local: { delivery: "local-only" },
          development: { delivery: "local-only" },
          staging: { delivery: "local-only" },
          production: { delivery: "local-only" }
        }
      },
      null,
      2
    )}\n`,
    "utf8"
  );
  await writeFile(
    join(rootDirectory, ".debugbundle", "local", "state.json"),
    `${JSON.stringify(
      {
        version: 1,
        last_processed_event_file: "20260321-0001-checkout.events.json",
        incidents: {
          inc_local_1: {
            incident_id: "inc_local_1",
            source: "local",
            project_id: "proj_local",
            service_id: "svc_checkout",
            service_name: "checkout-api",
            service_runtime: "Node.js",
            service_framework: "Fastify",
            environment: "development",
            fingerprint: "fp_1",
            fingerprint_version: "v1",
            title: "Checkout error",
            severity: "high",
            status: "open",
            first_seen_at: "2026-03-21T00:00:00.000Z",
            last_seen_at: "2026-03-21T00:00:00.000Z",
            occurrence_count: 1,
            source_event_id: "evt_1",
            source_occurred_at: "2026-03-21T00:00:00.000Z",
            source_event_types: ["backend_exception"],
            matched_fields: ["fingerprint"],
            bundle_path: ".debugbundle/bundles/local/inc_local_1.bundle.json",
            reproduction_path: ".debugbundle/bundles/local/reproductions/inc_local_1.reproduction.json",
            generation_number: 1
          }
        }
      },
      null,
      2
    )}\n`,
    "utf8"
  );

  return rootDirectory;
}

describe("cli connect command", () => {
  it("selects an existing cloud project, writes connected mode config, and keeps local investigation artifacts available", async () => {
    const rootDirectory = await createConnectFixtureRepository();

    const result = await connectCommand(
      {
        json: true
      },
      {
        cwd: () => rootDirectory,
        readAuthState: vi.fn().mockResolvedValue({
          bearer_token: "dbundle_mem_secret",
          base_url: "https://api.debugbundle.com"
        }),
        createProjectManagementApi: vi.fn().mockReturnValue({
          listProjects: vi.fn().mockResolvedValue([
            {
              project_id: "proj_cloud_existing",
              organization_id: "org_1",
              name: "Checkout App",
              slug: "checkout-app",
              environment_default: "production",
              plan: "free",
              metrics: {
                monthly_bundle_requests: 0,
                monthly_raw_ingested_events: 0,
                retained_bundles: 0,
                monthly_alert_deliveries: 0
              },
              created_at: "2026-03-21T00:00:00.000Z",
              updated_at: "2026-03-21T00:00:00.000Z"
            }
          ]),
          createProject: vi.fn()
        }),
        createTokenManagementApi: vi.fn().mockReturnValue({
          createProjectToken: vi.fn().mockResolvedValue({
            token_id: "ptok_1",
            plaintext: "dbundle_proj_secret"
          })
        })
      }
    );

    expect(result.exitCode).toBe(0);
    expect(JSON.parse(result.output)).toMatchObject({
      status: "healthy",
      checks: expect.arrayContaining([
        {
          name: "cloud-project",
          status: "ok",
          message: "Selected cloud project proj_cloud_existing (checkout-app)."
        },
        {
          name: "local-artifacts",
          status: "ok",
          message: "Local investigation artifacts remain available under .debugbundle/local/."
        }
      ]),
      warnings: [],
      errors: []
    });

    expect(JSON.parse(await readFile(join(rootDirectory, ".debugbundle", "local", "connection.json"), "utf8"))).toEqual({
      mode: "connected",
      cloud_project_id: "proj_cloud_existing",
      cloud_base_url: "https://api.debugbundle.com",
      environments: {
        local: { delivery: "local-only" },
        development: { delivery: "local-only" },
        staging: { delivery: "local-only" },
        production: { delivery: "cloud-enabled" }
      }
    });

    expect(JSON.parse(await readFile(join(rootDirectory, ".debugbundle", "local", "state.json"), "utf8"))).toMatchObject({
      incidents: {
        inc_local_1: {
          incident_id: "inc_local_1"
        }
      }
    });
  });

  it("creates a cloud project when none matches the local profile and surfaces the plaintext token in human output", async () => {
    const rootDirectory = await createConnectFixtureRepository();
    const createProject = vi.fn().mockResolvedValue({
      project_id: "proj_cloud_created",
      organization_id: "org_1",
      name: "Checkout App",
      slug: "checkout-app",
      environment_default: "production",
      plan: "free",
      metrics: {
        monthly_bundle_requests: 0,
        monthly_raw_ingested_events: 0,
        retained_bundles: 0,
        monthly_alert_deliveries: 0
      },
      created_at: "2026-03-21T00:00:00.000Z",
      updated_at: "2026-03-21T00:00:00.000Z"
    });

    const result = await connectCommand(
      {},
      {
        cwd: () => rootDirectory,
        readAuthState: vi.fn().mockResolvedValue({
          bearer_token: "dbundle_mem_secret",
          base_url: "https://api.debugbundle.com"
        }),
        createProjectManagementApi: vi.fn().mockReturnValue({
          listProjects: vi.fn().mockResolvedValue([]),
          createProject
        }),
        createTokenManagementApi: vi.fn().mockReturnValue({
          createProjectToken: vi.fn().mockResolvedValue({
            token_id: "ptok_2",
            plaintext: "dbundle_proj_created"
          })
        })
      }
    );

    expect(createProject).toHaveBeenCalledWith({
      bearerToken: "dbundle_mem_secret",
      name: "Checkout App",
      slug: "checkout-app",
      environmentDefault: "production"
    });
    expect(result.exitCode).toBe(0);
    expect(result.output).toContain("Created cloud project: Checkout App (proj_cloud_created)");
    expect(result.output).toContain("dbundle_proj_created");
  });

  it("returns an auth-config failure when stored member auth is missing", async () => {
    const rootDirectory = await createConnectFixtureRepository();

    const result = await connectCommand(
      {
        json: true
      },
      {
        cwd: () => rootDirectory,
        readAuthState: vi.fn().mockRejectedValue(new CliAuthStateError("auth_state_missing", "Not logged in."))
      }
    );

    expect(result.exitCode).toBe(2);
    expect(JSON.parse(result.output)).toMatchObject({
      status: "error",
      checks: expect.arrayContaining([
        {
          name: "cloud-connection",
          status: "error",
          message: "Not logged in."
        }
      ])
    });
  });

  it("returns early with success when the project is already connected", async () => {
    const rootDirectory = await createConnectFixtureRepository();

    await writeFile(
      join(rootDirectory, ".debugbundle", "local", "connection.json"),
      `${JSON.stringify(
        {
          mode: "connected",
          cloud_project_id: "proj_already_connected",
          cloud_base_url: "https://api.debugbundle.com",
          environments: {
            local: { delivery: "local-only" },
            development: { delivery: "local-only" },
            staging: { delivery: "local-only" },
            production: { delivery: "cloud-enabled" }
          }
        },
        null,
        2
      )}\n`,
      "utf8"
    );

    const humanResult = await connectCommand(
      {},
      {
        cwd: () => rootDirectory
      }
    );

    expect(humanResult.exitCode).toBe(0);
    expect(humanResult.output).toContain("already connected to cloud project proj_already_connected");

    const jsonResult = await connectCommand(
      {
        json: true
      },
      {
        cwd: () => rootDirectory
      }
    );

    expect(jsonResult.exitCode).toBe(0);
    expect(JSON.parse(jsonResult.output)).toMatchObject({
      status: "healthy",
      checks: expect.arrayContaining([
        {
          name: "connection-config",
          status: "ok",
          message: "Project is already connected to proj_already_connected."
        }
      ])
    });
  });

  it("returns a validation error when the profile has no setup scaffold", async () => {
    const rootDirectory = await mkdtemp(join(tmpdir(), "debugbundle-connect-no-profile-"));

    await mkdir(join(rootDirectory, ".debugbundle", "local"), { recursive: true });
    await writeFile(
      join(rootDirectory, ".debugbundle", "local", "connection.json"),
      `${JSON.stringify(
        {
          mode: "local-only",
          cloud_project_id: null,
          cloud_base_url: null,
          environments: {
            local: { delivery: "local-only" },
            development: { delivery: "local-only" },
            staging: { delivery: "local-only" },
            production: { delivery: "local-only" }
          }
        },
        null,
        2
      )}\n`,
      "utf8"
    );

    const result = await connectCommand(
      {
        json: true
      },
      {
        cwd: () => rootDirectory
      }
    );

    expect(result.exitCode).toBe(4);
    expect(JSON.parse(result.output)).toMatchObject({
      status: "error",
      errors: expect.arrayContaining([
        expect.stringContaining(".debugbundle/profile.json")
      ])
    });
  });

  it("maps project management API 400 errors to exit code 4", async () => {
    const rootDirectory = await createConnectFixtureRepository();

    const result = await connectCommand(
      {
        json: true
      },
      {
        cwd: () => rootDirectory,
        readAuthState: vi.fn().mockResolvedValue({
          bearer_token: "dbundle_mem_secret",
          base_url: "https://api.debugbundle.com"
        }),
        createProjectManagementApi: vi.fn().mockReturnValue({
          listProjects: vi.fn().mockRejectedValue(new ProjectManagementApiError(400, "invalid_request")),
          createProject: vi.fn()
        }),
        createTokenManagementApi: vi.fn().mockReturnValue({
          createProjectToken: vi.fn()
        })
      }
    );

    expect(result.exitCode).toBe(4);
    expect(JSON.parse(result.output)).toMatchObject({
      status: "error",
      errors: expect.arrayContaining([
        expect.stringContaining("400")
      ])
    });
  });

  it("maps project management API 401 errors to exit code 2", async () => {
    const rootDirectory = await createConnectFixtureRepository();

    const result = await connectCommand(
      {
        json: true
      },
      {
        cwd: () => rootDirectory,
        readAuthState: vi.fn().mockResolvedValue({
          bearer_token: "dbundle_mem_secret",
          base_url: "https://api.debugbundle.com"
        }),
        createProjectManagementApi: vi.fn().mockReturnValue({
          listProjects: vi.fn().mockRejectedValue(new ProjectManagementApiError(401, "unauthorized")),
          createProject: vi.fn()
        }),
        createTokenManagementApi: vi.fn().mockReturnValue({
          createProjectToken: vi.fn()
        })
      }
    );

    expect(result.exitCode).toBe(2);
    expect(JSON.parse(result.output)).toMatchObject({
      status: "error",
      errors: expect.arrayContaining([
        expect.stringContaining("401")
      ])
    });
  });

  it("maps project management API 404 errors to exit code 3", async () => {
    const rootDirectory = await createConnectFixtureRepository();

    const result = await connectCommand(
      {
        json: true
      },
      {
        cwd: () => rootDirectory,
        readAuthState: vi.fn().mockResolvedValue({
          bearer_token: "dbundle_mem_secret",
          base_url: "https://api.debugbundle.com"
        }),
        createProjectManagementApi: vi.fn().mockReturnValue({
          listProjects: vi.fn().mockRejectedValue(new ProjectManagementApiError(404, "not_found")),
          createProject: vi.fn()
        }),
        createTokenManagementApi: vi.fn().mockReturnValue({
          createProjectToken: vi.fn()
        })
      }
    );

    expect(result.exitCode).toBe(3);
    expect(JSON.parse(result.output)).toMatchObject({
      status: "error",
      errors: expect.arrayContaining([
        expect.stringContaining("404")
      ])
    });
  });

  it("maps token management API errors to the correct exit codes", async () => {
    const rootDirectory = await createConnectFixtureRepository();

    const result = await connectCommand(
      {
        json: true
      },
      {
        cwd: () => rootDirectory,
        readAuthState: vi.fn().mockResolvedValue({
          bearer_token: "dbundle_mem_secret",
          base_url: "https://api.debugbundle.com"
        }),
        createProjectManagementApi: vi.fn().mockReturnValue({
          listProjects: vi.fn().mockResolvedValue([
            {
              project_id: "proj_cloud_existing",
              organization_id: "org_1",
              name: "Checkout App",
              slug: "checkout-app",
              environment_default: "production",
              plan: "free",
              metrics: {
                monthly_bundle_requests: 0,
                monthly_raw_ingested_events: 0,
                retained_bundles: 0,
                monthly_alert_deliveries: 0
              },
              created_at: "2026-03-21T00:00:00.000Z",
              updated_at: "2026-03-21T00:00:00.000Z"
            }
          ]),
          createProject: vi.fn()
        }),
        createTokenManagementApi: vi.fn().mockReturnValue({
          createProjectToken: vi.fn().mockRejectedValue(new TokenManagementApiError(403, "forbidden"))
        })
      }
    );

    expect(result.exitCode).toBe(2);
    expect(JSON.parse(result.output)).toMatchObject({
      status: "error",
      errors: expect.arrayContaining([
        expect.stringContaining("403")
      ])
    });
  });
});