export const CLI_USAGE_LINES = [
  'Usage:',
  '  debugbundle analyze [--type <improvement|failure|performance>] [--local] [--json]',
  '  debugbundle doctor [--check-relay] [--json]',
  '  debugbundle setup [--non-interactive] [--json]',
  '  debugbundle connect [--auth-file <path>] [--json]',
  '  debugbundle ingest <file> --format <debugbundle-ndjson|php-error|apache-error> [--json]',
  '  debugbundle watch [--cloud] --log <file> --format <debugbundle-ndjson|php-error|apache-error> [--json]',
  '  debugbundle process [--json]',
  '  debugbundle clean [--events] [--bundles] [--all] [--older-than <Nd>] [--json]',
  '  debugbundle validate [--fix] [--json]',
  '  debugbundle verify local [--json]',
  '  debugbundle verify cloud --project-id <id> [--trigger-5xx] [--service <name>] [--environment <name>] [--max-age-minutes <n>] [--auth-file <path>] [--json]',
  '  debugbundle smoke --project-id <id> [--service <name>] [--environment <name>] [--max-age-minutes <n>] [--auth-file <path>] [--json]',
  '  debugbundle login <member-token> [--base-url <url>] [--auth-file <path>] [--json]',
  '  debugbundle login --github [--label <label>] [--base-url <url>] [--auth-file <path>] [--json]',
  '  debugbundle login --github-cli [--label <label>] [--base-url <url>] [--auth-file <path>] [--json]',
  '  debugbundle login --github-device [--label <label>] [--base-url <url>] [--auth-file <path>] [--json]',
  '  debugbundle profile validate [--json]',
  '  debugbundle whoami [--auth-file <path>] [--json]',
  '  debugbundle incidents [--source <local|cloud>] [--project-id <id>] [--environment <name>] [--service <name>] [--status <status>] [--severity <severity>] [--cursor <cursor>] [--limit <n>] [--auth-file <path>] [--json]',
  '  debugbundle inspect <incident-id> [--source <local|cloud>] [--auth-file <path>] [--json]',
  '  debugbundle explain <incident-id> [--source <local|cloud>] [--auth-file <path>] [--json]',
  '  debugbundle resolve <incident-id> [--source <local|cloud>] [--auth-file <path>] [--json]',
  '  debugbundle reopen <incident-id> [--source <local|cloud>] [--auth-file <path>] [--json]',
  '  debugbundle bundle <incident-id> [--source <local|cloud>] [--auth-file <path>] [--json]',
  '  debugbundle reproduce <incident-id> [--source <local|cloud>] [--auth-file <path>] [--json]',
  '  debugbundle logs <incident-id> [--level <level>] [--cursor <cursor>] [--limit <n>] [--auth-file <path>] [--json]',
  '  debugbundle services --project-id <id> [--limit <n>] [--auth-file <path>] [--json]',
  '  debugbundle billing get [--auth-file <path>] [--json]',
  '  debugbundle billing capacity increase --target-additional-capacity-units <n> [--auth-file <path>] [--json]',
  '  debugbundle billing capacity schedule-reduction --target-additional-capacity-units <n> [--auth-file <path>] [--json]',
  '  debugbundle billing capacity cancel-reduction [--auth-file <path>] [--json]',
  '  debugbundle github status [--project-id <id>] [--auth-file <path>] [--json]',
  '  debugbundle github repos [--auth-file <path>] [--json]',
  '  debugbundle github repo set <owner/repo> --project-id <id> [--auth-file <path>] [--json]',
  '  debugbundle github repo remove --project-id <id> [--auth-file <path>] [--json]',
  '  debugbundle github rules --project-id <id> [--auth-file <path>] [--json]',
  '  debugbundle github rules create --project-id <id> --name <name> --event <event[,event]> [--environment <env[,env]>] [--service <svc[,svc]>] --severity-min <level> --bundle-type <type> [--incident-status <status>] [--cooldown <seconds>] [--enabled <true|false>] [--auth-file <path>] [--json]',
  '  debugbundle github rules update <rule-id> --project-id <id> [--name <name>] [--event <event[,event]>] [--environment <env[,env]>] [--service <svc[,svc]>] [--severity-min <level>] [--bundle-type <type>] [--incident-status <status>] [--cooldown <seconds>] [--enabled <true|false>] [--auth-file <path>] [--json]',
  '  debugbundle github rules delete <rule-id> --project-id <id> [--auth-file <path>] [--json]',
  '  debugbundle github deliveries --project-id <id> [--status <status>] [--limit <n>] [--auth-file <path>] [--json]',
  '  debugbundle github deliveries retry <delivery-id> --project-id <id> [--auth-file <path>] [--json]',
  '  debugbundle project list [--limit <n>] [--auth-file <path>] [--json]',
  '  debugbundle project create --name <name> --slug <slug> [--environment-default <env>] [--auth-file <path>] [--json]',
  '  debugbundle project update <project-id> [--name <name>] [--slug <slug>] [--environment-default <env>] [--auth-file <path>] [--json]',
  '  debugbundle project delete <project-id> [--auth-file <path>] [--json]',
  '  debugbundle token project list <project-id> [--limit <n>] [--auth-file <path>] [--json]',
  '  debugbundle token project create <project-id> --label <label> [--auth-file <path>] [--json]',
  '  debugbundle token project revoke <project-id> <token-id> [--auth-file <path>] [--json]',
  '  debugbundle token member list [--limit <n>] [--auth-file <path>] [--json]',
  '  debugbundle token member create --label <label> [--auth-file <path>] [--json]',
  '  debugbundle token member revoke <token-id> [--auth-file <path>] [--json]',
  '  debugbundle alert list --project-id <id> [--limit <n>] [--auth-file <path>] [--json]',
  '  debugbundle alert create --project-id <id> --channel <channel> --condition <condition> [--service-id <id>] [--severity-min <level>] --config-json <json> [--is-enabled <true|false>] [--auth-file <path>] [--json]',
  '  debugbundle alert update <alert-id> [--service-id <id|null>] [--channel <channel>] [--condition <condition>] [--severity-min <level|null>] [--config-json <json|null>] [--is-enabled <true|false>] [--auth-file <path>] [--json]',
  '  debugbundle alert delete <alert-id> [--auth-file <path>] [--json]',
  '  debugbundle webhook list --project-id <id> [--limit <n>] [--auth-file <path>] [--json]',
  '  debugbundle webhook create --project-id <id> --url <url> --event <event[,event]> [--environment <env[,env]>] [--service <svc[,svc]>] [--severity-min <level>] [--bundle-type <type[,type]>] [--verification <true|false>] [--is-enabled <true|false>] [--auth-file <path>] [--json]',
  '  debugbundle webhook update <webhook-id> [--url <url>] [--event <event[,event]>] [--environment <env[,env]>] [--service <svc[,svc]>] [--severity-min <level>] [--bundle-type <type[,type]>] [--verification <true|false>] [--is-enabled <true|false>] [--auth-file <path>] [--json]',
  '  debugbundle webhook delete <webhook-id> [--auth-file <path>] [--json]',
  '  debugbundle webhook test <webhook-id> [--event <verification.passed|verification.failed>] [--auth-file <path>] [--json]',
  '  debugbundle webhook deliveries <webhook-id> [--limit <n>] [--auth-file <path>] [--json]',
  '  debugbundle webhook retry <webhook-id> <delivery-id> [--auth-file <path>] [--json]',
  '  debugbundle weekly-report list --project-id <id> [--limit <n>] [--auth-file <path>] [--json]',
  '  debugbundle weekly-report create --project-id <id> --channel <email|slack> --day-of-week <day> --hour-of-day <0-23> --timezone <iana> --config-json <json> [--is-enabled <true|false>] [--auth-file <path>] [--json]',
  '  debugbundle weekly-report update <channel-id> [--day-of-week <day>] [--hour-of-day <0-23>] [--timezone <iana>] [--config-json <json>] [--is-enabled <true|false>] [--auth-file <path>] [--json]',
  '  debugbundle weekly-report delete <channel-id> [--auth-file <path>] [--json]',
  '  debugbundle capture-policy get --project <id> [--auth-file <path>] [--json]',
  '  debugbundle capture-policy set --project <id> [--preset <minimal|balanced|investigative>] [--override <key=value>] [--auth-file <path>] [--json]',
  '  debugbundle probe activate <project-id> --label-pattern <pattern> [--service <name>] [--environment <name>] [--ttl-seconds <n>] [--trigger-ttl-seconds <n>] [--auth-file <path>] [--json]',
  '  debugbundle probe list <project-id> [--auth-file <path>] [--json]',
  '  debugbundle probe deactivate <project-id> <activation-id> [--auth-file <path>] [--json]',
  '  debugbundle member list [--auth-file <path>] [--json]',
  '  debugbundle member invites [--auth-file <path>] [--json]',
  '  debugbundle member invite --email <email> --role <owner|admin|member> [--auth-file <path>] [--json]',
  '  debugbundle member cancel-invite <invite-id> [--auth-file <path>] [--json]',
  '  debugbundle member update-role <user-id> --role <owner|admin|member> [--auth-file <path>] [--json]',
  '  debugbundle member remove <user-id> [--auth-file <path>] [--json]',
];

export function formatUsage(): string {
  return CLI_USAGE_LINES.join('\n');
}
