export const CLI_USAGE_LINES = [
  'Usage:',
  '  debugbundle --version',
  '  debugbundle -v',
  '  debugbundle -h',
  '  debugbundle analyze [--type <improvement|failure|performance>] [--local] [--json]',
  '  debugbundle doctor [--check-relay] [--json]',
  '  debugbundle setup [--non-interactive] [--json]',
  '  debugbundle connect [--auth-file <path>] [--json]',
  '  debugbundle ingest <file> --format <debugbundle-ndjson|php-error|apache-error> [--json]',
  '  debugbundle watch [--cloud] --log <file> --format <debugbundle-ndjson|php-error|apache-error> [--json]',
  '  debugbundle process [--preset <minimal|balanced|investigative>] [--json]',
  '  debugbundle clean [--events] [--bundles] [--all] [--older-than <Nd>] [--json]',
  '  debugbundle validate [--fix] [--json]',
  '  debugbundle verify local [--json]',
  '  debugbundle verify cloud --project-id <id> [--trigger-5xx | --trigger-4xx <400-499> | --expect-app-event [--trace-id <id>] [--request-id <id>]] [--service <name>] [--environment <name>] [--max-age-minutes <n>] [--auth-file <path>] [--json]',
  '  debugbundle smoke --project-id <id> [--service <name>] [--environment <name>] [--max-age-minutes <n>] [--auth-file <path>] [--json]',
  '  debugbundle login [--base-url <url>] [--auth-file <path>] [--json]',
  '  debugbundle login <member-token> [--base-url <url>] [--auth-file <path>] [--json]',
  '  debugbundle login --github [--label <label>] [--base-url <url>] [--auth-file <path>] [--json]',
  '  debugbundle login --github-cli [--label <label>] [--base-url <url>] [--auth-file <path>] [--json]',
  '  debugbundle login --github-device [--label <label>] [--base-url <url>] [--auth-file <path>] [--json]',
  '  debugbundle profile validate [--json]',
  '  debugbundle whoami [--auth-file <path>] [--json]',
  '  debugbundle incidents [--source <local|cloud>] [--project-id <id>] [--environment <name>] [--service <name>] [--status <active|open|resolved|regressed|all>] [--severity <severity>] [--first-seen-after <ISO8601>] [--attention-after <ISO8601>] [--cursor <cursor>] [--limit <n>] [--auth-file <path>] [--json]',
  '  debugbundle inspect <incident-id> [--source <local|cloud>] [--auth-file <path>] [--json]',
  '  debugbundle explain <incident-id> [--source <local|cloud>] [--auth-file <path>] [--json]',
  '  debugbundle resolve <incident-id> [incident-id ...] [--source <local|cloud>] [--auth-file <path>] [--json]',
  '  debugbundle reopen <incident-id> [incident-id ...] [--source <local|cloud>] [--auth-file <path>] [--json]',
  '  debugbundle bundle <incident-id> [--source <local|cloud>] [--auth-file <path>] [--json]',
  '  debugbundle reproduce <incident-id> [--source <local|cloud>] [--auth-file <path>] [--json]',
  '  debugbundle logs <incident-id> [--level <level>] [--cursor <cursor>] [--limit <n>] [--auth-file <path>] [--json]',
  '  debugbundle services --project-id <id> [--limit <n>] [--auth-file <path>] [--json]',
  '  debugbundle billing get [--auth-file <path>] [--json]',
  '  debugbundle billing trial start --plan <solo|team> [--auth-file <path>] [--json]',
  '  debugbundle billing capacity increase --target-additional-capacity-units <n> [--auth-file <path>] [--json]',
  '  debugbundle billing capacity schedule-reduction --target-additional-capacity-units <n> [--auth-file <path>] [--json]',
  '  debugbundle billing capacity cancel-reduction [--auth-file <path>] [--json]',
  '  debugbundle analytics settings get --project <id> [--auth-file <path>] [--json]',
  '  debugbundle analytics settings set --project <id> [--enabled <true|false>] [--privacy-mode <strict|standard|custom>] [--consent-required <true|false>] [--capture-page-views <true|false>] [--capture-route-changes <true|false>] [--capture-actions <true|false>] [--capture-friction-signals <true|false>] [--journey-sample-rate <0-1>] [--raw-retention-days <n>] [--sample-retention-days <n>] [--aggregate-retention-months <n>] [--max-saved-funnels <n>] [--max-custom-dimensions <n>] [--approved-custom-dimensions <key[,key]> | --approved-custom-dimensions-json <json>] [--auth-file <path>] [--json]',
  '  debugbundle analytics summary --project <id> [--from <ISO8601>] [--to <ISO8601>] [--last <duration>] [--granularity <hour|day>] [--service <name>] [--environment <name>] [--limit <n>] [--auth-file <path>] [--json]',
  '  debugbundle analytics routes --project <id> [--from <ISO8601>] [--to <ISO8601>] [--last <duration>] [--granularity <hour|day>] [--service <name>] [--environment <name>] [--limit <n>] [--auth-file <path>] [--json]',
  '  debugbundle analytics journeys --project <id> [--from <ISO8601>] [--to <ISO8601>] [--last <duration>] [--granularity <hour|day>] [--service <name>] [--environment <name>] [--limit <n>] [--auth-file <path>] [--json]',
  '  debugbundle analytics journey-samples list --project <id> [--service <name>] [--environment <name>] [--tag <tag>] [--cursor <cursor>] [--limit <n>] [--auth-file <path>] [--json]',
  '  debugbundle analytics journey-samples get <sample-id> --project <id> [--auth-file <path>] [--json]',
  '  debugbundle analytics devices --project <id> [--from <ISO8601>] [--to <ISO8601>] [--last <duration>] [--granularity <hour|day>] [--service <name>] [--environment <name>] [--limit <n>] [--auth-file <path>] [--json]',
  '  debugbundle analytics referrers --project <id> [--from <ISO8601>] [--to <ISO8601>] [--last <duration>] [--granularity <hour|day>] [--service <name>] [--environment <name>] [--limit <n>] [--auth-file <path>] [--json]',
  '  debugbundle analytics actions --project <id> [--from <ISO8601>] [--to <ISO8601>] [--last <duration>] [--granularity <hour|day>] [--service <name>] [--environment <name>] [--limit <n>] [--auth-file <path>] [--json]',
  '  debugbundle analytics funnels --project <id> [--from <ISO8601>] [--to <ISO8601>] [--last <duration>] [--granularity <hour|day>] [--service <name>] [--environment <name>] [--limit <n>] [--auth-file <path>] [--json]',
  '  debugbundle analytics incident-impact <incident-id> --project <id> [--from <ISO8601>] [--to <ISO8601>] [--last <duration>] [--granularity <hour|day>] [--service <name>] [--environment <name>] [--limit <n>] [--auth-file <path>] [--json]',
  '  debugbundle analytics funnel <funnel-key> --project <id> [--from <ISO8601>] [--to <ISO8601>] [--last <duration>] [--granularity <hour|day>] [--service <name>] [--environment <name>] [--limit <n>] [--auth-file <path>] [--json]',
  '  debugbundle analytics opportunities --project <id> [--status <open|resolved|snoozed|all>] [--kind <kind>] [--cursor <cursor>] [--limit <n>] [--auth-file <path>] [--json]',
  '  debugbundle analytics opportunity get <opportunity-id> --project <id> [--auth-file <path>] [--json]',
  '  debugbundle analytics bundle list --project <id> [--status <all|pending|running|completed|failed>] [--kind <kind>] [--cursor <cursor>] [--limit <n>] [--auth-file <path>] [--json]',
  '  debugbundle analytics bundle create --project <id> --kind <kind> [--from <ISO8601>] [--to <ISO8601>] [--last <duration>] [--funnel <key>] [--route <path>] [--incident-id <id>] [--deploy-id <id>] [--filters-json <json>] [--auth-file <path>] [--json]',
  '  debugbundle analytics bundle get <bundle-generation-id> --project <id> [--auth-file <path>] [--json]',
  '  debugbundle github status [--project-id <id>] [--auth-file <path>] [--json]',
  '  debugbundle github repos [--project-id <id>] [--auth-file <path>] [--json]',
  '  debugbundle github repo set <owner/repo> --project-id <id> [--auth-file <path>] [--json]',
  '  debugbundle github repo remove --project-id <id> [--auth-file <path>] [--json]',
  '  debugbundle github rules --project-id <id> [--auth-file <path>] [--json]',
  '  debugbundle github rules create --project-id <id> --name <name> --event <event[,event]> [--environment <env[,env]>] [--service <svc[,svc]>] --severity-min <level> --bundle-type <type> [--incident-status <status>] [--cooldown <seconds>] [--enabled <true|false>] [--auth-file <path>] [--json]',
  '  debugbundle github rules update <rule-id> --project-id <id> [--name <name>] [--event <event[,event]>] [--environment <env[,env]>] [--service <svc[,svc]>] [--severity-min <level>] [--bundle-type <type>] [--incident-status <status>] [--cooldown <seconds>] [--enabled <true|false>] [--auth-file <path>] [--json]',
  '  debugbundle github rules delete <rule-id> --project-id <id> [--auth-file <path>] [--json]',
  '  debugbundle github deliveries --project-id <id> [--status <status>] [--limit <n>] [--auth-file <path>] [--json]',
  '  debugbundle github deliveries retry <delivery-id> --project-id <id> [--auth-file <path>] [--json]',
  '  debugbundle project list [--limit <n>] [--auth-file <path>] [--json]',
  '  debugbundle project create --name <name> --slug <slug> [--environment-default <env>] [--color-tag <tag>] [--auth-file <path>] [--json]',
  '  debugbundle project update <project-id> [--name <name>] [--slug <slug>] [--environment-default <env>] [--color-tag <tag> | --clear-color-tag] [--auth-file <path>] [--json]',
  '  debugbundle project delete <project-id> [--auth-file <path>] [--json]',
  '  debugbundle token project list <project-id> [--limit <n>] [--auth-file <path>] [--json]',
  '  debugbundle token project create <project-id> --label <label> [--allowed-origin <origin> ...] [--auth-file <path>] [--json]',
  '  debugbundle token project revoke <project-id> <token-id> [--auth-file <path>] [--json]',
  '  debugbundle token member list [--limit <n>] [--auth-file <path>] [--json]',
  '  debugbundle token member create --label <label> [--auth-file <path>] [--json]',
  '  debugbundle token member revoke <token-id> [--auth-file <path>] [--json]',
  '  debugbundle alert list --project-id <id> [--limit <n>] [--auth-file <path>] [--json]',
  '  debugbundle alert create --project-id <id> --channel <channel> --condition <condition> [--service-id <id>] [--severity-min <level>] [--severity-lifecycle-scope <new_incident|incident_regressed|both>] [--cooldown <seconds>] --config-json <json> [--is-enabled <true|false>] [--auth-file <path>] [--json]',
  '  debugbundle alert update <alert-id> --project-id <id> [--service-id <id|null>] [--channel <channel>] [--condition <condition>] [--severity-min <level|null>] [--severity-lifecycle-scope <new_incident|incident_regressed|both|null>] [--cooldown <seconds>] [--config-json <json|null>] [--is-enabled <true|false>] [--auth-file <path>] [--json]',
  '  debugbundle alert delete <alert-id> --project-id <id> [--auth-file <path>] [--json]',
  '  debugbundle slack list --project-id <id> [--auth-file <path>] [--json]',
  '  debugbundle slack connect-url --project-id <id> [--return-to </projects/...>] [--auth-file <path>] [--json]',
  '  debugbundle slack test <destination-id> --project-id <id> [--auth-file <path>] [--json]',
  '  debugbundle slack delete <destination-id> --project-id <id> [--auth-file <path>] [--json]',
  '  debugbundle webhook list --project-id <id> [--limit <n>] [--auth-file <path>] [--json]',
  '  debugbundle webhook create --project-id <id> --url <url> --event <event[,event]> [--environment <env[,env]>] [--service <svc[,svc]>] [--severity-min <level>] [--bundle-type <type[,type]>] [--verification <true|false>] [--is-enabled <true|false>] [--auth-file <path>] [--json]',
  '  debugbundle webhook update <webhook-id> --project-id <id> [--url <url>] [--event <event[,event]>] [--environment <env[,env]>] [--service <svc[,svc]>] [--severity-min <level>] [--bundle-type <type[,type]>] [--verification <true|false>] [--is-enabled <true|false>] [--auth-file <path>] [--json]',
  '  debugbundle webhook delete <webhook-id> --project-id <id> [--auth-file <path>] [--json]',
  '  debugbundle webhook test <webhook-id> --project-id <id> [--event <verification.passed|verification.failed>] [--auth-file <path>] [--json]',
  '  debugbundle webhook deliveries <webhook-id> --project-id <id> [--limit <n>] [--auth-file <path>] [--json]',
  '  debugbundle webhook retry <webhook-id> <delivery-id> --project-id <id> [--auth-file <path>] [--json]',
  '  debugbundle weekly-report list --project-id <id> [--limit <n>] [--auth-file <path>] [--json]',
  '  debugbundle weekly-report create --project-id <id> --channel <email|slack> --day-of-week <day> --hour-of-day <0-23> --timezone <iana> --config-json <json> [--is-enabled <true|false>] [--auth-file <path>] [--json]',
  '      email --config-json uses {"to":["owner@example.com"]} with up to 3 recipients',
  '  debugbundle weekly-report update <channel-id> [--day-of-week <day>] [--hour-of-day <0-23>] [--timezone <iana>] [--config-json <json>] [--is-enabled <true|false>] [--auth-file <path>] [--json]',
  '  debugbundle weekly-report delete <channel-id> [--auth-file <path>] [--json]',
  '  debugbundle capture-policy get --project <id> [--auth-file <path>] [--json]',
  '  debugbundle capture-policy set --project <id> [--preset <minimal|balanced|investigative>] [--override <key=value>] [--client-error-incidents <preset-default|none|recommended|custom>] [--client-error-statuses <400,401,...>] [--client-error-path-rule <404=/path/*@GET,POST>] [--client-error-path-rules-json <json|null>] [--auth-file <path>] [--json]',
  '  debugbundle capture-rule list --project-id <id> [--auth-file <path>] [--json]',
  '  debugbundle capture-rule suggest <incident-id> [--auth-file <path>] [--json]',
  '  debugbundle capture-rule create-from-suggestion <incident-id> --suggestion-id <id> [--name <name>] [--description <text>] [--enabled <true|false>] [--expires-at <ISO8601>] [--auth-file <path>] [--json]',
  '  debugbundle capture-rule create --project-id <id> --name <name> --action <demote|sample|drop> --matcher-json <json> [--description <text>] [--enabled <true|false>] [--sample-rate <0-1>] [--sample-event-class <preserve|context>] [--expires-at <ISO8601>] [--auth-file <path>] [--json]',
  '  debugbundle capture-rule update <rule-id> --project-id <id> [--name <name>] [--description <text>] [--enabled <true|false>] [--action <demote|sample|drop>] [--matcher-json <json>] [--sample-rate <0-1>] [--sample-event-class <preserve|context>] [--expires-at <ISO8601>] [--auth-file <path>] [--json]',
  '  debugbundle capture-rule delete <rule-id> --project-id <id> [--auth-file <path>] [--json]',
  '  debugbundle improvements list [--project-id <id>] [--environment <name>] [--service <name>] [--status <status>] [--severity <level>] [--kind <kind>] [--cursor <cursor>] [--limit <n>] [--auth-file <path>] [--json]',
  '  debugbundle improvements get <improvement-id> [--auth-file <path>] [--json]',
  '  debugbundle improvements bundle <improvement-id> --project-id <id> [--auth-file <path>] [--json]',
  '  debugbundle improvements resolve <improvement-id> [--auth-file <path>] [--json]',
  '  debugbundle improvements reopen <improvement-id> [--auth-file <path>] [--json]',
  '  debugbundle improvements snooze <improvement-id> --until <ISO8601> [--auth-file <path>] [--json]',
  '  debugbundle improvements settings get --project <id> [--auth-file <path>] [--json]',
  '  debugbundle improvements settings set --project <id> [--enabled <true|false>] [--sensitivity <high_confidence|balanced|verbose>] [--auth-file <path>] [--json]',
  '  debugbundle probe activate <project-id> --label-pattern <pattern> [--service <name>] [--environment <name>] [--ttl-seconds <n>] [--trigger-ttl-seconds <n>] [--auth-file <path>] [--json]',
  '  debugbundle probe list <project-id> [--auth-file <path>] [--json]',
  '  debugbundle probe deactivate <project-id> <activation-id> [--auth-file <path>] [--json]',
  '  debugbundle health checks list --project-id <id> [--limit <n>] [--auth-file <path>] [--json]',
  '  debugbundle health checks get <check-id> --project-id <id> [--auth-file <path>] [--json]',
  '  debugbundle health checks create --project-id <id> --name <name> --url <url> --interval-seconds <n> [--method <GET|HEAD>] [--expected-status-min <code>] [--expected-status-max <code>] [--timeout-ms <n>] [--failure-threshold <n>] [--recovery-threshold <n>] [--environment <name>] [--service <name|null>] [--enabled <true|false>] [--auth-file <path>] [--json]',
  '  debugbundle health checks update <check-id> --project-id <id> [--name <name>] [--url <url>] [--method <GET|HEAD>] [--expected-status-min <code>] [--expected-status-max <code>] [--timeout-ms <n>] [--interval-seconds <n>] [--failure-threshold <n>] [--recovery-threshold <n>] [--environment <name>] [--service <name|null>] [--enabled <true|false>] [--auth-file <path>] [--json]',
  '  debugbundle health checks delete <check-id> --project-id <id> [--auth-file <path>] [--json]',
  '  debugbundle health checks test --project-id <id> --url <url> [--method <GET|HEAD>] [--expected-status-min <code>] [--expected-status-max <code>] [--timeout-ms <n>] [--auth-file <path>] [--json]',
  '  debugbundle health checks results <check-id> --project-id <id> [--limit <n>] [--auth-file <path>] [--json]',
  '  debugbundle health checks daily-rollups <check-id> --project-id <id> [--limit <n>] [--auth-file <path>] [--json]',
  '  debugbundle project members list --project-id <id> [--auth-file <path>] [--json]',
  '  debugbundle project members invites --project-id <id> [--auth-file <path>] [--json]',
  '  debugbundle project members invite --project-id <id> --email <email> --role <admin|member> [--auth-file <path>] [--json]',
  '  debugbundle project members cancel-invite <invite-id> --project-id <id> [--auth-file <path>] [--json]',
  '  debugbundle project members update-role <user-id> --project-id <id> --role <admin|member> [--auth-file <path>] [--json]',
  '  debugbundle project members remove <user-id> --project-id <id> [--auth-file <path>] [--json]',
  '  debugbundle project members leave --project-id <id> [--auth-file <path>] [--json]',
];

export function formatUsage(): string {
  return CLI_USAGE_LINES.join('\n');
}
